apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    # spec:
    #   securityContext:
    #     fsGroup: 33
    #     runAsUser: 33
    #     runAsGroup: 33

      containers:
        - name: audiobookshelf
          image: advplyr/audiobookshelf:2.29.0
          ports:
            - containerPort: 3005
      #     envFrom:
      #       # - configMapRef:
      #       #     name: linkding-configmap
      #       - secretRef:
      #           name: linkding-container-env
      #     securityContext:
      #       allowPrivilegeEscalation: false   

      #     volumeMounts:
      #       - name: linkding-data
      #         mountPath: etc/linkding/data

      # volumes:
      #   - name: linkding-data
      #     persistentVolumeClaim:
      #       claimName: linkding-data-pvc
