apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
        - name: audiobookshelf
          image: advplyr/audiobookshelf:2.29.0
          ports:
            - containerPort: 3005
          # env:
          #   - name: PORT 
          #     value: "3005"
          envFrom:
            - configMapRef:
               name: audiobookshelf-configmap
            # - secretRef:
            #     name: linkding-container-env
          securityContext:
            allowPrivilegeEscalation: false   

          volumeMounts:
            - name: audiobookshelf-storage
              mountPath: /audiobookshelf
            - name: podcasts-storage
              mountPath: /podcasts
            - name: config-storage
              mountPath: /config
            - name: metadata-storage
              mountPath: /metadata
            

      volumes:
        - name: audiobookshelf-storage
          persistentVolumeClaim:
            claimName: audiobookshelf-storage-pvc
        - name: podcasts-storage
          persistentVolumeClaim:
            claimName: podcasts-storage-pvc
        - name: config-storage
          persistentVolumeClaim:
            claimName: config-storage-pvc
        - name: metadata-storage
          persistentVolumeClaim:
            claimName: metadata-storage-pvc

# repush
